### PR TITLE
Remove hard-coded reference to "localhost" and construct url from public attr

### PR DESCRIPTION
**Pull request by oxtopus**

### CODE REVIEW

**Comment by oxtopus** [comment]
@chetan51 I don't know how to bundle these changes into the API.unitypackage file.  I could use your help, there.

**Comment by chetan51** [comment]
@oxtopus 
1. Open `unity-plugin/src` as a project in Unity.
2. In the menu bar, select `Assets > Export Package`.
3. Make sure everything is selected, and click `Export`.
4. Save to replace the `API.unitypackage` file.

**Comment by oxtopus** [comment]
Thanks!  Updated.

**Comment by chetan51** [comment]
Thanks!

**Pull request merged**
